services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    restart: always
    environment:
      POSTGRES_DB: SII_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passwort
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

  pygeoapi:
    image: geopython/pygeoapi:latest
    container_name: pygeoapi
    restart: always
    depends_on:
      - postgis
    ports:
      - "5000:80"
    volumes:
      - ./pygeoapi-config.yml:/pygeoapi/local.config.yml
    environment:
      PYGEOAPI_CONFIG: /pygeoapi/local.config.yml
      PYGEOAPI_OPENAPI: /pygeoapi/openapi.yml

volumes:
  postgis_data:
