server:
  url: http://localhost:5000
  bind: 0.0.0.0:80
  cors: true

logging:
  level: DEBUG

providers:
  - type: feature
    name: gis
    data:
      dialect: postgis
      host: localhost
      port: 5432
      dbname: gis
      user: docker
      password: docker
      search_path: public
